# Generated by Django 5.0.1 on 2024-01-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0004_alter_book_slug'),
        ('book_outlet', '0004_auto_20210119_1021'),
    ]

    operations = [
    ]
