# Generated by Django 5.0.1 on 2024-01-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0010_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_counties',
            field=models.ManyToManyField(related_name='books', to='book_outlet.country'),
        ),
    ]
